NAMA : Mohammad Iqbal Surya Ramadhan

NIM  : 210411100002

MATA KULIAH : Pencarian dan Penambangan Web - A

# Tugas 7 : Klasifikasi Berita Metode Logistic Regression dengan reduksi dimensi deploy reduksi dimensi berita

Deploy Streamlit

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/PPWA/report/Tugas-PPWA/Hasil_Prepros.csv")
df.head()

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,"Nunggak 8 Bulan, Segini Pajak Ford Mustang Mil...","Kamis, 19 Sep 2024 13:05 WIB",Jakarta - Bareskrim Polri menyita aset senilai...,Otomotif,Jakarta Bareskrim Polri menyita aset senilai ...,jakarta bareskrim polri menyita aset senilai ...,"['jakarta', 'bareskrim', 'polri', 'menyita', '...",jakarta bareskrim polri menyita aset senilai r...
1,Bos Ford Kaget usai Jajal Mobil China: Mereka ...,"Kamis, 19 Sep 2024 12:33 WIB","Jakarta - Chief Executive Officer (CEO) Ford, ...",Otomotif,Jakarta Chief Executive Officer CEO Ford Jim ...,jakarta chief executive officer ceo ford jim ...,"['jakarta', 'chief', 'executive', 'officer', '...",jakarta chief executive officer ceo ford jim f...
2,"Tarif Tol Dalam Kota Naik Jadi Segini, Berlaku...","Kamis, 19 Sep 2024 12:08 WIB",Jakarta - Jasa Marga mengumumkan kenaikan tari...,Otomotif,Jakarta Jasa Marga mengumumkan kenaikan tarif...,jakarta jasa marga mengumumkan kenaikan tarif...,"['jakarta', 'jasa', 'marga', 'mengumumkan', 'k...",jakarta jasa marga mengumumkan kenaikan tarif ...
3,Pak RT Aleix Espargaro Tak Sabar Balapan Terak...,"Kamis, 19 Sep 2024 11:40 WIB","Jakarta - Pebalap Aprilia asal Spanyol, Aleix ...",Otomotif,Jakarta Pebalap Aprilia asal Spanyol Aleix Es...,jakarta pebalap aprilia asal spanyol aleix es...,"['jakarta', 'pebalap', 'aprilia', 'asal', 'spa...",jakarta pebalap aprilia spanyol aleix espargar...
4,Angkot Listrik Bakal Diuji Coba di Jakarta,"Kamis, 19 Sep 2024 11:18 WIB",Jakarta - PT Transportasi Jakarta (TransJakart...,Otomotif,Jakarta PT Transportasi Jakarta TransJakarta ...,jakarta pt transportasi jakarta transjakarta ...,"['jakarta', 'pt', 'transportasi', 'jakarta', '...",jakarta pt transportasi jakarta transjakarta k...

Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Transformasi data kategorik
label_encoder = LabelEncoder()
df.loc[:, 'kategori_encoded'] = label_encoder.fit_transform(df['kategori'])

# Menampilkan nilai sebelum dan sesudah konversi
print("\nNilai sebelum dan sesudah konversi:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nDataFrame setelah Label Encoding:")
df

Nilai sebelum dan sesudah konversi:
{'Keuangan': 0, 'Otomotif': 1}

DataFrame setelah Label Encoding:

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal,kategori_encoded
0,"Nunggak 8 Bulan, Segini Pajak Ford Mustang Mil...","Kamis, 19 Sep 2024 13:05 WIB",Jakarta - Bareskrim Polri menyita aset senilai...,Otomotif,Jakarta Bareskrim Polri menyita aset senilai ...,jakarta bareskrim polri menyita aset senilai ...,"['jakarta', 'bareskrim', 'polri', 'menyita', '...",jakarta bareskrim polri menyita aset senilai r...,1
1,Bos Ford Kaget usai Jajal Mobil China: Mereka ...,"Kamis, 19 Sep 2024 12:33 WIB","Jakarta - Chief Executive Officer (CEO) Ford, ...",Otomotif,Jakarta Chief Executive Officer CEO Ford Jim ...,jakarta chief executive officer ceo ford jim ...,"['jakarta', 'chief', 'executive', 'officer', '...",jakarta chief executive officer ceo ford jim f...,1
2,"Tarif Tol Dalam Kota Naik Jadi Segini, Berlaku...","Kamis, 19 Sep 2024 12:08 WIB",Jakarta - Jasa Marga mengumumkan kenaikan tari...,Otomotif,Jakarta Jasa Marga mengumumkan kenaikan tarif...,jakarta jasa marga mengumumkan kenaikan tarif...,"['jakarta', 'jasa', 'marga', 'mengumumkan', 'k...",jakarta jasa marga mengumumkan kenaikan tarif ...,1
3,Pak RT Aleix Espargaro Tak Sabar Balapan Terak...,"Kamis, 19 Sep 2024 11:40 WIB","Jakarta - Pebalap Aprilia asal Spanyol, Aleix ...",Otomotif,Jakarta Pebalap Aprilia asal Spanyol Aleix Es...,jakarta pebalap aprilia asal spanyol aleix es...,"['jakarta', 'pebalap', 'aprilia', 'asal', 'spa...",jakarta pebalap aprilia spanyol aleix espargar...,1
4,Angkot Listrik Bakal Diuji Coba di Jakarta,"Kamis, 19 Sep 2024 11:18 WIB",Jakarta - PT Transportasi Jakarta (TransJakart...,Otomotif,Jakarta PT Transportasi Jakarta TransJakarta ...,jakarta pt transportasi jakarta transjakarta ...,"['jakarta', 'pt', 'transportasi', 'jakarta', '...",jakarta pt transportasi jakarta transjakarta k...,1
...,...,...,...,...,...,...,...,...,...
95,Suku Bunga BI Dipangkas Jadi 6% Dinilai Berani,"Rabu, 18 Sep 2024 21:15 WIB",Jakarta - Bank Indonesia (BI) memutuskan untuk...,Keuangan,Jakarta Bank Indonesia BI memutuskan untuk me...,jakarta bank indonesia bi memutuskan untuk me...,"['jakarta', 'bank', 'indonesia', 'bi', 'memutu...",jakarta bank indonesia bi memutuskan menurunka...,0
96,Prabowo Ingatkan Perang Makin Marak hingga Sal...,"Rabu, 18 Sep 2024 21:00 WIB",Jakarta - Presiden terpilih Prabowo Subianto m...,Keuangan,Jakarta Presiden terpilih Prabowo Subianto me...,jakarta presiden terpilih prabowo subianto me...,"['jakarta', 'presiden', 'terpilih', 'prabowo',...",jakarta presiden terpilih prabowo subianto men...,0
97,"Ditjen Pajak Respons Kabar 6 Juta NPWP Bocor, ...","Rabu, 18 Sep 2024 20:36 WIB",Jakarta - Direktorat Jenderal Pajak (DJP) Keme...,Keuangan,Jakarta Direktorat Jenderal Pajak DJP Kemente...,jakarta direktorat jenderal pajak djp kemente...,"['jakarta', 'direktorat', 'jenderal', 'pajak',...",jakarta direktorat jenderal pajak djp kementer...,0
98,Buruh Waswas Kisruh di Kadin Pengaruhi Penetap...,"Rabu, 18 Sep 2024 20:30 WIB",Jakarta - Presiden Partai Buruh yang juga Pres...,Keuangan,Jakarta Presiden Partai Buruh yang juga Presi...,jakarta presiden partai buruh yang juga presi...,"['jakarta', 'presiden', 'partai', 'buruh', 'ya...",jakarta presiden partai buruh presiden konfede...,0
99,PIS Beberkan Rencana Tekan Emisi Karbon di Mas...,"Rabu, 18 Sep 2024 20:19 WIB",Jakarta - Bisnis berkelanjutan dengan emisi ka...,Keuangan,Jakarta Bisnis berkelanjutan dengan emisi kar...,jakarta bisnis berkelanjutan dengan emisi kar...,"['jakarta', 'bisnis', 'berkelanjutan', 'dengan...",jakarta bisnis berkelanjutan emisi karbon rend...,0

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
# Memisahkan fitur dan label
x = df['stopword_removal']
y = df['kategori_encoded']

In [ ]:
# Membagi data menjadi data latih dan data uji
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# Tahap 1: TF-IDF
tfidf_vectorizer = TfidfVectorizer()
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

# Mengonversi hasil TF-IDF menjadi DataFrame
df_train_tfidf = pd.DataFrame(x_train_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
df_test_tfidf = pd.DataFrame(x_test_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
print("Hasil TF-IDF (Data Latih):")
df_train_tfidf

Hasil TF-IDF (Data Latih):

,abang,abdullah,absen,ac,acara,acaraacara,accord,acdkil,acdrrd,aceh,...,zaman,zeekr,zenix,zero,ziko,zimbabwe,zona,zs,zulkifli,zz
0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
2,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.00000,0.0,0.0,0.0,0.000000,0.056665,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.04273,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
76,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.579384,0.0,0.0,0.0,0.0
77,0.00000,0.0,0.0,0.0,0.027113,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
78,0.00000,0.0,0.0,0.0,0.023880,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.030164,0.0,0.000000,0.0,0.0,0.0,0.0
79,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0

In [ ]:
# Tahap 2: SVD (Reduksi Dimensi)
svd = TruncatedSVD(n_components=100, random_state=42)
x_train_svd = svd.fit_transform(x_train_tfidf)
x_test_svd = svd.transform(x_test_tfidf)

# Mengonversi hasil SVD menjadi DataFrame
df_train_svd = pd.DataFrame(x_train_svd)
df_test_svd = pd.DataFrame(x_test_svd)
print("\nHasil SVD (Data Latih):")
df_train_svd

Hasil SVD (Data Latih):

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,0.151420,0.008995,-0.002330,0.009450,0.112772,0.022204,0.054448,0.012579,-0.035239,0.023470,...,0.052499,-0.006736,0.018344,0.014128,-0.011256,0.005249,0.011810,0.025089,0.020389,-0.000484
1,0.099354,-0.030823,0.032536,0.098444,0.060560,0.050479,0.126619,-0.011214,-0.015239,-0.029698,...,-0.000883,0.008089,0.004754,0.006326,0.004287,0.011374,-0.003007,0.003680,-0.002699,0.000562
2,0.086412,-0.051942,0.063853,0.077714,-0.001710,0.310604,-0.141642,0.112706,0.515787,-0.128591,...,0.031666,-0.011851,0.044961,0.023392,0.050647,0.007913,0.008582,-0.000707,0.001598,0.000473
3,0.171193,-0.065436,-0.007130,0.170107,0.012458,0.054828,0.026655,0.088889,-0.027723,0.047524,...,0.012858,-0.003342,-0.001259,0.007186,0.003342,0.002312,0.008631,-0.008073,0.000107,0.000526
4,0.087258,-0.001783,0.001554,0.066566,0.013678,0.038728,0.047805,0.083340,-0.014152,-0.032336,...,-0.002760,0.005533,0.018506,0.022534,0.009196,-0.002087,0.002662,-0.003779,0.004468,0.000374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.064509,-0.002701,0.052313,0.011031,-0.011490,0.043808,-0.006289,0.001646,-0.028082,0.032700,...,-0.008530,0.012487,-0.001167,-0.005575,0.008723,-0.005453,0.011149,0.002317,-0.000534,0.001091
76,0.026674,0.006677,0.006909,0.027950,0.033533,0.000173,0.057178,0.005962,-0.010295,-0.003969,...,0.024250,0.010574,-0.007465,-0.000617,-0.002249,-0.000778,0.003758,0.000616,0.000373,-0.000074
77,0.067158,-0.032598,0.014750,0.059325,-0.004929,0.058630,0.014094,0.033669,-0.014599,-0.002991,...,-0.002967,-0.001656,0.003203,0.005928,-0.005846,0.002272,0.000432,0.010005,0.004232,-0.000743
78,0.172072,-0.038748,0.042435,0.235186,0.113633,0.093361,0.178112,0.555071,-0.198464,-0.183973,...,0.058869,-0.062949,-0.090591,-0.017570,-0.006569,0.017925,-0.001722,0.008698,-0.004899,-0.000042
79,0.109256,-0.067858,0.014429,0.027550,0.053566,0.092037,-0.027051,0.222795,0.150803,0.083087,...,0.010110,0.014156,-0.141521,-0.066314,-0.037037,-0.013841,-0.007465,-0.005470,0.016581,-0.000149

In [ ]:
# Tahap 3: Klasifikasi dengan Logistic Regression
clf = LogisticRegression( random_state=42)
clf.fit(x_train_svd, y_train)
y_pred = clf.predict(x_test_svd)

In [ ]:
# Evaluasi Model
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

Pengujian

In [ ]:
import joblib
from sklearn.pipeline import Pipeline

# Misalnya, Anda telah membuat pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('x_train_svd', TruncatedSVD(n_components=100)),
    ('clf', LogisticRegression())
])

# Setelah melatih model
pipeline.fit(x_train, y_train)

# Menyimpan pipeline
joblib.dump(pipeline, 'svd_tfidf_pipeline.pkl')

['svd_tfidf_pipeline.pkl']

In [ ]:
import joblib
import pandas as pd

# Memuat pipeline yang telah disimpan
pipeline = joblib.load('svd_tfidf_pipeline.pkl')

# Teks baru yang ingin diprediksi
new_text_1 = ['''Jakarta - Sebelum membalap di Sirkuit Mandalika (27/9), sejumlah rider MotoGP akan melakukan parade di kawasan Mataram, Lombok, Nusa Tenggara Barat (NTB). Kabar baiknya, setelah sempat diragukan hadir, Marc Marquez dipastikan ikut acara tersebut! Kepastian Marc Marquez ikut parade MotoGP di Lombok disampaikan Lalu Martawang selaku Asisten 1 Setda Kota Mataram. Menurutnya, Marquez akan ditemani pebalap Moto2 asli Indonesia, Mario Aji. "Pebalap ini akan diiringi atau dikawal oleh sejumlah penggemar motor yang ada di daerah ini," ujar Lalu Martawang setelah mengadakan rapat persiapan parade bersama dengan sejumlah panitia MotoGP Mandalika, dikutip dari Antara , Selasa (17/9). MotoGP Mandalika Foto: ANTARA FOTO/Andika Wahyu Menurut jadwal atau rundown acara, para pebalap akan melakukan parade mulai pukul 16.00 WITA dari depan Taman Sangkareang Jalan Pejanggik, menuju ke arah barat dan finis di Teras Udayana. Berbeda dengan parade di Jakarta tahun lalu, pebalap yang ikut parade di Lombok tak naik motor, melainkan naik mobil khusus yang sudah disiapkan panitia. Tujuannya, agar mereka bisa lebih leluasan menyapa masyarakat setempat tanpa menggunakan helm atau penutup kepala. Lalu berharap, kegiatan tersebut bisa berjalan dengan lancar. Dia mau masyarakat setempat tetap kondusif saat hendak menyapa para pebalap. "Mari kita meriahkan dan buktikan kita adalah tuan rumah terbaik yang bisa menyapa tamu-tamu," ungkapnya. Marc Marquez ikut parade di Mandalika. Foto: REUTERS/Pablo Morano Sementara Project Director Side Event MotoGP Mandalika 2024 Edison Wardana mengatakan, panitia akan menggelar hiburan kreatif dan permainan berhadiah ketika parade tersebut finis di Terasa Udayana. Ada ratusan hadiah menarik yang bakal dibagikan. "Kami juga sudah menyiapkan 7.000 bendera dan balon tepuk untuk anak-anak sekolah yang akan menyemarakkan parade," kata Edison. (sfn/din)''']

new_text_2 = ['''Jakarta - Bisnis berkelanjutan dengan emisi karbon rendah menjadi urgensi bagi entitas di seluruh dunia termasuk PT Pertamina International Shipping (PIS). PIS membeberkan rencana bisnis jangka pendek dan jangka panjang mulai dari energi alternatif seperti biofuel hingga kesiapan di pengembangan bisnis pengangkutan dan penyimpanan karbon. Rencana tersebut dipaparkan perusahaan dalam forum internasional di Shipbuilding, Machinery and Marine (SMM) Hamburg, Jerman. Direktur Manajemen Armada PIS M. Irfan Zainul Fikri hadir sebagai salah satu pembicara di forum internasional ternama yang membahas industri maritim tersebut. Di hadapan para perwakilan industri maritim dunia, Irfan menyebutkan bahwa PIS tengah bertransformasi menjadi perusahaan modern dengan operasional dan model bisnis yang ramah lingkungan. Ia juga menegaskan PIS menargetkan menekan 30% total emisi karbon mereka pada 2030 nanti. "Strategi kami melibatkan investasi pada pengembangan dan adopsi bahan bakar rendah emisi seperti biofuel, LNG, amonia, dan metanol, untuk mengoperasikan armada kami," ucap Irfan dalam sesi panel mengenai masa depan masa depan maritim awal September lalu seperti dalam keterangan tertulis, Rabu (18/9/2024). Sejumlah kapal dari lini armada PIS, khususnya yang beroperasi di domestik, telah menggunakan biofuel sebagai bahan bakar, didukung oleh infrastruktur biofuel Pertamina. Selain itu, kapal-kapal baru yang akan datang juga tengah disiapkan untuk penggunaan bahan bakar alternatif rendah karbon. Seperti MR Tankers dengan implementasi teknologi dual-fuel-ready LNG dan Handysize LPG dengan teknologi dual-fuel-ready amonia. Belum lagi kehadiran armada Very Large Gas Carrier (VLGC) juga berbahan bakar dual-fuel-ready amonia. Tak hanya itu, Irfan juga menyebut bahwa PIS sedang menjajal sumber energi baru seperti baterai dan hidrogen di masa depan. Selain armada green ships, bahan bakar alternatif, dan green terminal, PIS juga mulai merambah bisnis carbon capture storage (CCS)/carbon capture utilize storage (CCUS). Potensi bisnis dari sektor ini merentang mulai dari pengantaran, penyimpanan, injeksi, hingga infrastruktur terminal karbon. Untuk memasuki bisnis tersebut, PIS bersiap dengan investasi pada kapal pengangkut LCO2 (liquid carbon dioxide) dan receiving terminal. "Yang terpenting saat ini adalah kami harus memastikan ketersediaan pemasok dalam rute operasional dan mempersiapkan armada kami berteknologi dual-fuel. Kami menargetkan sebagian besar armada kami akan bertenaga bahan bakar rendah karbon, agar dapat berkontribusi dalam upaya dunia untuk mengurangi emisi gas rumah kaca," imbuh Irfan. Seluruh strategi ini merupakan wujud keseriusan PIS sebagai pemain utama di sektor logistik energi di Asia Tengara untuk memimpin upaya dekarbonisasi, selaras dengan tujuan International Maritime Organization (IMO) dan komitmen Pertamina mencapai Net Zero Emission pada 2060. Guna mewujudkan komitmen tersebut, PIS menargetkan menurunkan 30% dari total emisi karbon dalam operasional perusahaan di akhir 2030. Seluruh inisiatif ini menunjukkan keseriusan PIS dalam mempraktikkan bisnis yang berkelanjutan di tengah upaya perusahaan memenuhi ketahanan energi nasional. PIS juga memastikan bahwa transformasi hijau terus berlangsung sesuai dengan Sustainable Development Goals (SDGs) serta upaya penerapan Environmental, Social, Governance (ESG) di seluruh lini bisnis dan operasional perusahaan. (akd/ega)''']

# Gabungkan kedua teks menjadi satu list
new_text = new_text_1 + new_text_2


# Melakukan prediksi dengan pipeline
predictions = pipeline.predict(new_text)

# Hasil prediksi
predicted_categories = ["Keuangan" if predictions ==  0 else "Otomotif" for predictions in predictions]

# Output hasil prediksi untuk masing-masing teks
for i, category in enumerate(predicted_categories):
    print(f"Prediksi untuk teks {i+1}: {category}")

Prediksi untuk teks 1: Otomotif
Prediksi untuk teks 2: Keuangan